services:
  postgres:
    image: postgres:15-alpine
    container_name: liftify-postgres
    environment:
      POSTGRES_DB: liftify-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"  # Expose to host
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 10s
      timeout: 5s
      retries: 5

#  redis:
#    image: redis:7-alpine
#    container_name: ecom-redis
#    ports:
#      - "6379:6379"
#    volumes:
#      - redis_data:/data

    #   rabbitmq:
    #   image: rabbitmq:3-management-alpine
    #   container_name: ecom-rabbitmq
      #    environment:
      #     RABBITMQ_DEFAULT_USER: admin
    #     RABBITMQ_DEFAULT_PASS: admin123
        #   ports:
        #      - "5672:5672"   # AMQP - expose to host
    #     - "15672:15672" # Management UI
        #   volumes:
  #     - rabbitmq_data:/var/lib/rabbitmq

volumes:
  postgres_data:
  # redis_data:
  # rabbitmq_data: